name: scanner
description: A new Flutter package project.
version: 3.0.1
homepage: https://github.com/fanchungchit/scanner

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  collection: ^1.17.0
  flutter:
    sdk: flutter
  honeywell_scanner: ^4.0.0+14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
