name: scanner
description: A new Flutter package project.
version: 5.0.0
homepage: https://github.com/fanchungchit/scanner

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  collection:
  honeywell_scanner:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
